### ISSUE TITLE
how to do aggregation with feathers-objection?

### ISSUE THREAD

**Issue by ranielzed** [feathersjs-ecosystem/feathers-objection#101]
I noticed that there are no examples when doing aggregation with feathers-objection.
How should it be done? I can't seem to find any.

I just need to do a simple sum and group by.
Please direct me to where I can find more information.

Thank you.

**Comment by dekelev** [comment]
GROUP BY queries are not supported in feathers-objection and can be run directly with [knex](https://knexjs.org/#Builder-groupBy).

**Comment by ranielzed** [comment]
@dekelev, thank you for your prompt answer. I appreciate it a lot.
Can you guide me on how that can be done or can you refer me to an example? Not really sure how to reach knex from feathers-objection -> objection -> knex.

**Comment by dekelev** [comment]
Sure. Take a look at the [Initializing the Library section](https://github.com/feathersjs-ecosystem/feathers-objection#initializing-the-library) in the docs.

You'll see that inside your `objection.js` file, you should run `app.set('knex', knex)`, so to run query with Knex directly later, you simply need to get it back from the app with `const knex = app.get('knex')` and use it like this: `knex.raw('SELECT * FROM ...')` or use its built-in methods like this: `knex('users').groupBy(...)`.

**Comment by robbyphillips** [comment]
Just to add, you should also be able to access the Objection model from the service like `app.service('users').Model` to use Objection's query builder.

`app.service('users').Model.query().groupBy(...)`

**Comment by ranielzed** [comment]
@dekelev, @robbyphillips Thank you for these. These are very helpful

**Comment by avimar** [comment]
Also, you should be able to write the query inside the model and expose it via the `modify` functionality https://github.com/feathersjs-ecosystem/feathers-objection#query-operators and https://vincit.github.io/objection.js/api/query-builder/other-methods.html#modify

**Comment by philipimperato** [comment]
Any idea on how to reset the `select` so that I don't have to include the `Model.id`?
