### ISSUE TITLE
Project permission issue

### ISSUE THREAD

**Issue by dekelev** [feathersjs-ecosystem/feathers-objection#106]
Hi @daffl 

I'm unable to push merged branches commits to the master branch after Travis test success (it may be a travis issue). this was possible until recently. Are you aware of any change that could have cause that? I don't have access to the project settings.

Thanks!

**Comment by dekelev** [comment]
Seems like a Travis issue

**Comment by daffl** [comment]
I updated your permission to admin so you should have full access to the repo and Travis now.

**Comment by dekelev** [comment]
Thanks!
