### ISSUE TITLE
Relate

### ISSUE THREAD

**Issue by Thomas-git** [feathersjs-ecosystem/feathers-objection#110]
Is it possible to do a relate query as in objection doc : 
https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#relate

If yes, how can I do that ?

**Comment by dekelev** [comment]
You can call any custom ObjectionJS method you want on the query-builder object using model's [modifiers](https://github.com/feathersjs-ecosystem/feathers-objection#query-operators), which runs before the query actually executes.
