### ISSUE TITLE
How can I override the default model?

### ISSUE THREAD

**Issue by sokulski** [feathersjs-ecosystem/feathers-objection#116]
When using the Feathers CLI to generate a model, some hooks are created that don't fit in with my data models.

I'd look to be able to modify the default model, specifically so that I can not have the $beforeInsert and $beforeUpdate hooks in the model.

Is that possible?

**Comment by dekelev** [comment]
Sure, check out Objection.js BaseModel in here:
https://vincit.github.io/objection.js/guide/models.html#examples

בתאריך יום ה׳, 17 בספט׳ 2020, 23:55, מאת sokulski ‏<notifications@github.com
