### ISSUE TITLE
Query customization: Can all where clauses be enclosed in parentheses after they have been added?

### ISSUE THREAD

**Issue by mikeconley12** [feathersjs-ecosystem/feathers-objection#119]
#### Code example

```js
app.service("todos").hooks({
  before: {
    find(context) {
      const query = context.service.createQuery(context.params);
      // Adds an access check. Example "select `todos`.* from `todos` where `text` = ? and `userId` = ?"
      query.andWhere("userId", context.params.user.id);
      context.params.objection = query;
      return context;
    }
  }
});
```

The above example has a security bug. If the `.createQuery(...)` generates a query like this: 

```sql
select `todos`.* from `todos` where `text` = ? or `id` = ?
```

Then after adding the access check we will get the following query:

```sql
select `todos`.* from `todos` where `text` = ? or `id` = ? and `userId` = ?
```

And this query can return data that doesn't belong to the current user.
To fix this bug, we need to enclose the user-controlled conditions in parentheses:

```sql
select `todos`.* from `todos` where (`text` = ? or `id` = ?) and `userId` = ?
```

**But how do I do this with the Objection.js database adapter?** I imagine something like this:

```js
const query = context.service.createQuery(context.params);
wrapWhereClauses(query);
query.andWhere("userId", context.params.user.id);
```

**Comment by dekelev** [comment]
@mikeconley12 `createQuery` method is meant to be used internally, but in any way, using `$or` in your `context.params.query` is the supported way to add `OR` condition in your query and it will add parentheses around the condition.

**Comment by mikeconley12** [comment]
> @mikeconley12 `createQuery` method is meant to be used internally.

@dekelev I thought this adapter works like the Knex service adapter and the Knex service adapter has the `createQuery` method exposed. See [Customizing the query](https://github.com/feathersjs-ecosystem/feathers-knex#customizing-the-query) in docs. 

It would be great to have the same feature here, because this is the only place where I can use SQL subqueries.

**Comment by dekelev** [comment]
I'm not sure what you mean by SQL subqueries. Maybe share your use-case.

You can always call the context.service.find method internally in your
project and achieve the same.

בתאריך שבת, 17 באוק׳ 2020, 14:55, מאת mikeconley12 ‏<
notifications@github.com>:

**Comment by mikeconley12** [comment]
> I'm not sure what you mean by SQL subqueries. Maybe share your use-case

```js
app.service("events").hooks({
  before: {
    find(context) {
      const query = context.service.createQuery(context.params);
      query.whereIn('calendarId', function() {
        this
          .select('id')
          .from('calendars')
          .where('userId', context.params.user.id);
      });
      context.params.objection = query;
      return context;
    }
  }
});
```

> You can always call the context.service.find method internally in your project and achieve the same

Don't really get it. Could you please explain?

**Comment by dekelev** [comment]
I ment that if you are using createQuery method, which is used internally
by the service find method. So why not just call the find method? The
library was built in a way that if you call the the find method, you can
pass a query param with all sort of supported operators, like $or.

בתאריך שבת, 17 באוק׳ 2020, 15:38, מאת mikeconley12 ‏<
notifications@github.com>:

**Comment by mikeconley12** [comment]
> So why not just call the find method?

Because I can't use subqueries in the `find` method

**Comment by dekelev** [comment]
Maybe you can use model's modifiers to use more of ObjectionJS/Knex
features. Check the docs for examples.

בתאריך שבת, 17 באוק׳ 2020, 16:13, מאת mikeconley12 ‏<
notifications@github.com>:

**Comment by mikeconley12** [comment]
Thanks for the answers!
