### ISSUE TITLE
Bug: Query customization doesn't apply to the count SQL query

### ISSUE THREAD

**Issue by mikeconley12** [feathersjs-ecosystem/feathers-objection#120]
I created a reproduction repository: https://github.com/mikeconley12/feathers-objection .
See the changes: https://github.com/feathersjs-ecosystem/feathers-objection/compare/master...mikeconley12:master

#### Steps to reproduce
1. `git clone https://github.com/mikeconley12/feathers-objection.git`
2. `cd feathers-objection/`
3. `npm i`
4. `DEBUG=knex:query npm run example`
5. Open http://localhost:3030/todos?text=foo in a browser

In your terminal, you should see the following:

```
  knex:query select count(`todos`.`id`) as `total` from `todos` where `text` = ? undefined +5s
  knex:query select `todos`.* from `todos` where `text` = ? and `complete` = ? limit ? undefined +3ms
```

The first SQL query doesn't have the `` `complete` = ?`` condition, but the second SQL query has this condition.

**Comment by dekelev** [comment]
Please open bugs with informative description and examples.

**Comment by mikeconley12** [comment]
I'm sorry if I'm not clear. Let me explain.

I customize the query in [my example](https://github.com/feathersjs-ecosystem/feathers-objection/compare/master...mikeconley12:master) (this is an undocumented feature, but the documentation says: "It works like the Knex service adapter", and the Knex service adapter has [customizing the query](https://github.com/feathersjs-ecosystem/feathers-knex#customizing-the-query)  feature).

But my [modifications](https://github.com/mikeconley12/feathers-objection/blob/master/example/app.js#L47) to the query don't apply to the count SQL query. See logs:

```
  knex:query select count(`todos`.`id`) as `total` from `todos` where `text` = ? undefined +5s
  knex:query select `todos`.* from `todos` where `text` = ? and `complete` = ? limit ? undefined +3ms
```

I think the problem may be this:

You use `params.objection` [here](https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/index.js#L474),

```js
const q = params.objection || this.createQuery(params);
```

But in the count query, you [don't use](https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/index.js#L511) `params.objection`

```js
const countQuery = this._createQuery(params);
```

**Comment by dekelev** [comment]
"It works like the Knex service adapter" - in no point this lib was ment to
be like the Knex service adapter.

This lib was forked from the Knex service lib years ago and was built in a
different way.

Please read the docs (README).

בתאריך שבת, 17 באוק׳ 2020, 15:27, מאת mikeconley12 ‏<
notifications@github.com>:

**Comment by mikeconley12** [comment]
Thanks for the answers!
