### ISSUE TITLE
Poor performance of the create operation

### ISSUE THREAD

**Issue by mikeconley12** [feathersjs-ecosystem/feathers-objection#125]
[This library executes an SQL insert query for each data item](https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/index.js#L631). Futhermore, after insert, it executes SQL select queries to load the created records (only if `$noSelect` is false). I think this can be improved by using bulk operations.

Objection.js methods used in the `_create` method take an array as an argument.

* [upsertGraphAndFetch](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#upsertgraphandfetch) . By the way, can we use `upsertGraph` instead of `upsertGraphAndFetch`? `upsertGraph` should improve performance
* [insertGraph](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#insertgraph)
* [insert](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#insert)

**Comment by dekelev** [comment]
Hi @mikeconley12,  Batch insert support might be possible. The returned data would probably be based on the input data as no `SELECT` would be performed for improved performance, which is an obvious need when you resort to a batching insert solution. I use Knex directly when I need to do a batch insert.

I've implemented something similar in feathers-cassandra, so when the [`$batch` query operator](https://github.com/feathersjs-ecosystem/feathers-cassandra#special-query-operators) is set to true, the insert is done in batches with the support of the underlying library & driver:

`upsertGraph` should be preferred over `upsertGraphAndFetch` when the `$noSelect` query operator is set to true.
I'm not sure what's the current behavior there, but you can check. I'm personally not using the insertGraph/upsertGraph features.
