### ISSUE TITLE
Is it possible to assign a default eagerness to the response when a user logs in?

### ISSUE THREAD

**Issue by sokulski** [feathersjs-ecosystem/feathers-objection#126]
I'm using a hook to add a default eagerness if one isn't provided when querying for specific things.

However, I can't seem to find a way to do this for the user object that is returned when a user logs in. It'd be great if I could hook into this query somewhere, but I can't seem to locate where that hook would be registered.

Any assistance you can provide would be much appreciated.

**Comment by dekelev** [comment]
Hi @sokulski, You can read more on FeathersJS auth strategies [here](https://docs.feathersjs.com/api/authentication/strategy.html).

For customizing the query that return a user object in login, you will need to extend the default local strategy class.
For example, [here](https://docs.feathersjs.com/api/authentication/local.html#customization) is the docs for how to customize the `getEntityQuery` method in a local strategy, which runs in login.
