### ISSUE TITLE
SQL queries and database errors are exposed in HTTP responses

### ISSUE THREAD

**Issue by mikeconley12** [feathersjs-ecosystem/feathers-objection#129]
Steps to reproduce:

1. Clone this repository: `git clone https://github.com/feathersjs-ecosystem/feathers-objection.git`
2. `cd feathers-objection`
3. `npm i`
4. `npm run example`
5. Send an HTTP request to the server: 

	```bash
	curl 'http://127.0.0.1:3030/todos' -X POST -H "content-type: application/json" -d '{"text": "foo", "nonexistentColumn": "bar"}'
	```

You should see the following response: 

```
{"name":"GeneralError","message":"insert into `todos` (`complete`, `createdAt`, `nonexistentColumn`, `text`, `updatedAt`) values (false, '2020-11-09T17:46:43.342Z', 'bar', 'foo', '2020-11-09T17:46:43.342Z') - SQLITE_ERROR: table todos has no column named nonexistentColumn","code":500,"className":"general-error","errors":{}}
```

I think SQL queries and database errors in HTTP responses are a security issue.

**Comment by dekelev** [comment]
5xx errors' messages needs to be hidden within your FeathersJS error
handler, right after you log these errors in your log systems.

בתאריך יום ב׳, 9 בנוב׳ 2020, 19:58, מאת mikeconley12 ‏<
notifications@github.com>:

**Comment by dekelev** [comment]
https://docs.feathersjs.com/api/errors.html#server-side-errors

You should remove the stack too in 5xx errors

בתאריך יום ב׳, 9 בנוב׳ 2020, 21:11, מאת Dekel ‏<dekelev@gmail.com>:

**Comment by mikeconley12** [comment]
Thanks for the answer!
