### ISSUE TITLE
Error handling is not working correctly for Postgres

### ISSUE THREAD

**Issue by GVanderLugt** [feathersjs-ecosystem/feathers-objection#130]
### Issue

My user model requires emails to be unique. If I try to create a user with a duplicate email address I get a 500 error with the DB error as the message.

```
GeneralError: insert into "users" ("created_on", "email", "isVerified", "name", "password", "updated_on", "verifyChanges", "verifyExpires", "verifyShortToken", "verifyToken") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - duplicate key value violates unique constraint "users_email_unique"
```

### Debugging

I've been trying to debug in `error-handler.js`. It looks like this error just isn't being handled. The incoming error object has all the necessary info to return a well formed Feathers error, but it's not doing anything.

### Code

I have a very simple user service that looks like this:

`users.service.ts`
```typescript
// Initializes the `user` service on path `/user`
import { ServiceAddons } from '@feathersjs/feathers';
import { Application } from '../../declarations';
import Users from './users.class';
import UserModel, { UserType } from '../../models/user.model';
import hooks from './users.hooks';

// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    users: Users & ServiceAddons<UserType>;
  }
}

export default function (app: Application) {
  const options = {
    Model: UserModel,
    paginate: app.get('paginate'),
  };

  // Initialize our service with any options it requires
  app.use('/users', new Users(options, app));

  // Get our initialized service so that we can register hooks
  const service = app.service('users');

  service.hooks(hooks);
}
```

`users.class.ts`
```typescript
import UserModel, { UserType } from '../../models/user.model';
import Base from '../base.class';

export default class Users extends Base<UserType, UserModel> {}
```

`base.class` is very simple and is simply extending `feathers-objection.Service` with some extra typing.

### Dependencies
```javascript
{
    "feathers-objection": "^6.1.1",
    "objection": "^2.2.3",
    "pg": "^8.4.1",
    "knex": "^0.21.6",
}
```

**Comment by GVanderLugt** [comment]
When I log the incoming error in `error-handler.js` it looks like it's an instance of an Objection `UniqueViolationError` and it's just not being handled correctly.

**Comment by robbyphillips** [comment]
Is there a reason that the error handler doesn't look more like the objection recipe here: https://vincit.github.io/objection.js/recipes/error-handling.html#examples ?

**Comment by dekelev** [comment]
You can always access the original error instance via a Symbol. check [here](https://github.com/feathersjs-ecosystem/feathers-objection#error-handling) for more info.

**Comment by GVanderLugt** [comment]
@robbyphillips I'm wondering the same thing. It looks like the error handler is trying to handle Objection errors according to [this](https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/error-handler.js#L32) comment. However, that block is never executing because `error.statusCode` is not defined.
