### ISSUE TITLE
Calling Stored Procedures

### ISSUE THREAD

**Issue by madhuraadawadkar** [feathersjs-ecosystem/feathers-objection#132]
How can I invoke a stored procedure using objectionjs?
I tried invoking with knex by using 
`knex.raw('Call TEST_SP(1);')`
It was executed correctly and got the result in Raw format (row values in TextRow object).
How do I convert this result to json, so I can send it in response?

**Comment by dekelev** [comment]
ObjectionJS does not support calling functions/procedures, so it can only be done with [knex](http://knexjs.org/) directly. you can read more about it [here](https://github.com/Vincit/objection.js/issues/380).
