### ISSUE TITLE
How to write custom endpoint

### ISSUE THREAD

**Issue by prashantnirgun** [feathersjs-ecosystem/feathers-objection#154]
Hi this is Prashant, I am new to Feathers and Objection

I am very sorry its not an Issue just need help from community. I installed "@feathersjs/feathers": "^4.5.11". Now my question is If I want to write routes http://localhost:3000/contact/india or any custom endpoint for GET, POST methods where do I write can you guide me. Basically wants a controller but that does not mean I want to use create() and other methods of Objection should fire automatically don't want to override the methods provided by Objection.js

I know we can query it by http://localhost:3000/contact?country="India" but need need build custom routes. Controller kind of where I will write custom endpont related to that service rest create, update and other methods should be handle automatically If required then will overwrite create().

Thanks in advance

**Comment by daffl** [comment]
I highly recommend walking through the guide and learning about services ([Quickstart](https://docs.feathersjs.com/guides/basics/starting.html#installing-feathers) and in more detail in the [chat guide](https://docs.feathersjs.com/guides/basics/services.html) and the service [API docs](https://docs.feathersjs.com/api/services.html)). You can create your own service by choosing a "Custom service" when calling `feathers generate service`.
