### ISSUE TITLE
support of feathers dove v5

### ISSUE THREAD

**Issue by nour-dev** [feathersjs-ecosystem/feathers-objection#157]
is feathersjs dove v5 supported with this package ?

**Comment by dekelev** [comment]
Sorry, but I have no idea. I'm not working with Feathers for almost half a year now, so if anyone would like to test for Feathers v5, he's more than welcome to do so. If any issues are found, it can be listed here or in a PR. thanks!

**Comment by marshallswain** [comment]
This package should already work with Feathers v5 Dove, but I've opened an issue to make the required changes to make it official: https://github.com/feathersjs-ecosystem/feathers-objection/issues/171.  Closing this issue in favor of that one.
