### ISSUE TITLE
Can I cast a field from the client side and have it reflected in the db query? 

### ISSUE THREAD

**Issue by philipimperato** [feathersjs-ecosystem/feathers-objection#172]
I'm trying to search on a field using `$ilike` but the field is an integer. 

Using Postgres

The query is simple `amount::text $ilike '%100%'`. I would like to be able to indicate this from the clientside, but I can't seem to figure it out as the db will always wrap it with double quotes and throw an error. 

This is what the query looks like:
 `where (("amount::text" ilike '%100%'))`

This is the postgres / objection error: 
`operator does not exist: integer ~~* unknown`

**Comment by nhelgeson-wsb** [comment]
I have the same question - what ended up being the solution? I would like to pass in a query like below but the fields are integers. My work around is to create a custom modifier and sql query where I can cast the fields to a number.

```
    "$or": [
        {
            "metadata": {
                "t_and_e.i_hours": {
                    "$like": "%1%"
                }
            }
        },
        {
            "metadata": {
                "t_and_e.i_hours": {
                    "$gt": "10"
                }
            }
        }
    ]
```
