### ISSUE TITLE
Moving to feathers ecosystem organization?

### ISSUE THREAD

**Issue by mcchrish** [feathersjs-ecosystem/feathers-objection#43]
It has been a while since I've worked on a project using feathers (I would love to in the future!) and unfortunately been MIA in maintaining this adapter. Huge thanks to @dekelev for extending and improving this adapter and covering more use cases I didn't imagine before.

Now I'm wondering if this repo can benefit by moving to the community maintained org https://github.com/feathersjs-ecosystem giving it more visibility and for people who might use it and also improve it further.

What do you think? @dekelev @daffl @ekryski

**Comment by daffl** [comment]
Sounds good to me. I added you to the organization so I _think_ you should be able to move it. Let me know if there is anything else needed.

**Comment by mcchrish** [comment]
>You don’t have the permission to create repositories on feathersjs-ecosystem 

@daffl can't change yet.

**Comment by daffl** [comment]
It says that when you try to [transfer the repository](https://help.github.com/articles/transferring-a-repository/#transferring-a-repository-owned-by-your-personal-account)?

**Comment by mcchrish** [comment]
Sorry for the late reply. Yes, that's what it says when going through those steps. Not sure if a work around this works via transferring mcchrish->daffl->feathers-ecosystem. Preserving the sound permission of the org members.

**Comment by daffl** [comment]
Just changed the permission, I think it should work now.
