### ISSUE TITLE
Virtual attribute breakage with Objection 1.6.4+

### ISSUE THREAD

**Issue by Aerlin** [feathersjs-ecosystem/feathers-objection#45]
Virtual attributes aren't being added to results after updating Objection to 1.6.4+.  I think [this issue](https://github.com/Vincit/objection.js/pull/1258) is related. 

For example, trying to stringify Objection's results won't include virtual attributes. 
```
Comment.query().then(function(results) {
	console.log("comments " + JSON.stringify( results , null, "\t"));
})
```

I think Feathers-Objection is affected by this. Unsure if it's something F-O can fix or if it needs to be fixed on Objection's end. But reverting to objection@1.6.3 works for now.

**Comment by dekelev** [comment]
@Aerlin Did you try with Objection.js latest version 1.6.6?

**Comment by Aerlin** [comment]
Yeah. I double checked now and 1.6.6 is affected. 

Example of my setup
```
// models/Comment.js
const { Model, snakeCaseMappers } = require('objection');
const moment = require('moment');
const md = require('markdown-it')({
  html: true,
  linkify: true,
  typographer: true
});
...
module.exports = function(app) {
	class Comment extends Model {
		static get tableName() {
			return 'comments';
		}
		static get virtualAttributes() {
		  return ['created_ago', 'updated_ago', 'html'];
		}
		created_ago() {
		  return this.created_at &&  moment( this.created_at.getTime() ).fromNow(true);
		}

		updated_ago() {
		  return this.updated_at && moment( this.updated_at.getTime() ).fromNow(true);
		}

		html() {
		 // console.log("Comment html()");
		  return this.body && md.render(this.body);
		}
	}
	...
}
```

```
// Elsewhere.
const Comment = require('../models/Comment.js')(app);
var builder = Comment.query().then(function(results) {
	console.log("comments " + JSON.stringify( results , null, "\t"));
}).catch(function(err) {
	console.trace(err);
});
```

In Objection@1.6.3, the query results contain the created_ago, updated_ago and html fields. In 1.6.4, 1.6.5 & 1.6.6 the fields are missing. I know this isn't Feathers-Objection's fault. Just wanted to let you know the issue was affecting F-O. Although I'm starting to wonder if I broke something as nobody else seems to be reporting the issue on the Objection issues list. 😕

**Comment by Aerlin** [comment]
Objection's Model virtuals parameter used to default to true, now defaults to false. 

[(https://github.com/Vincit/objection.js/commit/55303773da82e196b732803f112118fcc3bee9b2#diff-008bf8359e2b2c171c571598395ecfb7L22]((https://github.com/Vincit/objection.js/commit/55303773da82e196b732803f112118fcc3bee9b2#diff-008bf8359e2b2c171c571598395ecfb7L22)

[https://github.com/Vincit/objection.js/commit/8115f0bc50794a5aed40337c39bf71ff60c4bee6#diff-008bf8359e2b2c171c571598395ecfb7R52](https://github.com/Vincit/objection.js/commit/8115f0bc50794a5aed40337c39bf71ff60c4bee6#diff-008bf8359e2b2c171c571598395ecfb7R52)

If getVirtuals is set to default to true, the missing virtual attributes return.
```
function getVirtuals(opt) {
  if (!opt) {
    return true;
  } else if (Array.isArray(opt.virtuals)) {
    return opt.virtuals;
  } else if (opt.virtuals) {
    return true;
  } else {
    return true; // <--------------
  }
}
```

I 'm not sure if the change was intended and F-O needs to implicitly requests virtuals somewhere now, or if it's a bug that they can fix.

**Comment by koskimas** [comment]
This is a bug in objection. Sorry about this. I'm releasing 1.6.7 right now with a fix.

**Comment by koskimas** [comment]
https://github.com/Vincit/objection.js/commit/df277ea105f5cc46b607993f3b9550265b325864

**Comment by koskimas** [comment]
objection 1.6.7 is now released.
