### ISSUE TITLE
Patching record with query, causes NotFound error to be thrown

### ISSUE THREAD

**Issue by ewingrj** [feathersjs-ecosystem/feathers-objection#49]
If I have a model that looks like:

```
Record {
  id: string,
  name: string
  status: string
}
```

When running the following patch call:

```
app.services('records').patch(id, {status: 'old'}, {query: {status: 'new'}});
```

The db will be successfully updated, however a NotFound error is thrown. This appears to happen b/c the record is updated, and then directly fetched using the id & query params that were provided. However one of those query params has been updated as a result of the patch.

It seems like it would be better to track the PK's of the records that were patched & use that to fetch the records again, or to disable the query param for patchs. The current behavior is not very clear.

**Comment by dekelev** [comment]
Hi @ewingrj I'm familiar with this issue and also use try-catch as a workaround. It is not trivial, but it seems to be the expected behavior with Feathers DB adapters, which all share this [test](https://github.com/feathersjs/feathers/blob/master/packages/adapter-tests/lib/methods.js#L290).

**Comment by Elytum** [comment]
Hi ! Therefore, how to know if the patch worked or not, because the try/catch doesn't give informations ? Sure, we could query before or after, but what about race condition then ?

**Comment by dekelev** [comment]
If you know that the query will fail with 404 error since you just patched the property that you queried on, then you can use the `$noSelect` query operator to skip the SELECT query after the UPDATE query. your return data will be based only on the data input for the `patch` method.
