### ISSUE TITLE
Present demo application with working relations

### ISSUE THREAD

**Issue by domagoj-orioly** [feathersjs-ecosystem/feathers-objection#54]
Can you give us an example of working application with actual relations between models because I cannot get stuff like `allowEager`, `eagerFilters` to work like it's described in the documentation.

**Comment by ap1969** [comment]
I second this, 2 years later!

**Comment by dekelev** [comment]
I've added a relation to the example app. You can check the code [here](https://github.com/feathersjs-ecosystem/feathers-objection/tree/master/example).

Use `npm  run example` to run the app locally.
