### ISSUE TITLE
Typescript types not found

### ISSUE THREAD

**Issue by jakobrosenberg** [feathersjs-ecosystem/feathers-objection#56]
Just rolled a Feathers app with Typescript and Objection. After ``npm run dev`` I get the following error:

``Could not find a declaration file for module 'feathers-objection'. ``

Additionally I get the error ``Cannot find name 'Application'`` in the autogenerated user.class.ts

EDIT
Unlike feathers-knex, there's no types folder in node_modules/feathers-objection

**Comment by DenisVK** [comment]
@jakobrosenberg Hi, did you find any solution? Have the same issue.

**Comment by vonagam** [comment]
There is pending PR #48 which should fix it.

**Comment by DenisVK** [comment]
Typescript declarations issue is resolved, but errors are still here:

`src/services/users/users.class.ts(8,47): error TS2304: Cannot find name 'Application'.`

`src/services/users/users.class.ts(13,7): error TS2345: Argument of type '{ model: any; idSeparator?: string | undefined; jsonSchema?: any; allowedEager?: string | undefined; namedEagerFilters?: any; eagerFilters?: any; allowedInsert?: any; insertGraphOptions?: any; ... 8 more ...; filters?: string[] | undefined; }' is not assignable to parameter of type 'Partial<ObjectionServiceOptions>'.
  Object literal may only specify known properties, but 'model' does not exist in type 'Partial<ObjectionServiceOptions>'. Did you mean to write 'Model'?`

**Comment by daffl** [comment]
Fixed in v4.2.3
