### ISSUE TITLE
Support sorting on jsonb columns

### ISSUE THREAD

**Issue by ewingrj** [feathersjs-ecosystem/feathers-objection#58]
With objection, you can refer to jsonb columns using a [FieldExpression](https://vincit.github.io/objection.js/api/types/#type-fieldexpression). You can wrap those in a [ref](https://vincit.github.io/objection.js/api/objection/#ref) to include them in any part of the query.

If would be great if the feathers adapter supported this. Especially with `$sort`, `$pick`, `$select`, etc

**Comment by roelvan** [comment]
I wrote a simple "add sorting" hooking to solve my needs, for those interested:
```
const { checkContext } = require('feathers-hooks-common');

module.exports = function(field = 'name') {
  return async context => {
    checkContext(context, 'before');
    const { query = {} } = context.params;

    if (!field || field.length < 1) {
      throw new Error('Invalid sort field.');
    }

    // sort field is not present, ignore then
    if (!(query?.$sort && query.$sort[field])) return context;

    const language = query.$sort[field].en ? 'en' : 'nl';
    const order = parseInt(
      query.$sort[field][language] || query.$sort[field],
      10
    );
    delete query.$sort[field];
    const objection = context.service.createQuery(context.params);
    objection.orderByRaw(
      `${field} ->> '${language}' ${order < 0 ? 'DESC' : 'ASC'}`
    );
    context.params.objection = objection;

    return context;
  };
};
```
In my hooks file I use it like this: `addI18nSorting('name')`

**Comment by dekelev** [comment]
v3.5.0 now supports `$select` & `$sort` with `ref`. [docs examples](https://github.com/feathersjs-ecosystem/feathers-objection#query-operators).
