### ISSUE TITLE
Typescript compile error

### ISSUE THREAD

**Issue by DenisVK** [feathersjs-ecosystem/feathers-objection#60]
Getting next error while Typescript compile:

`[ERROR] 18:56:46 ⨯ Unable to compile TypeScript:
src/services/users/users.class.ts(8,47): error TS2304: Cannot find name 'Application'.`

Tested on 4.2.3 version.

**Comment by dekelev** [comment]
@daffl any idea?

**Comment by indrayn** [comment]
It is missing the `import { Application } from '../declarations';` and also every generated by `feathers g service` missing `import { Application } from '../../declarations';` in `src/models/xxx.model.ts`
And also there's a warning the first time the table created, for example:
```
(node:33208) Warning: a promise was created in a handler at internal/timers.js:439:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Users/indra/work/tutorial/Feathers/work/appcore/node_modules/bluebird/js/release/method.js:29:9)
Created users table
```
