### ISSUE TITLE
don't use countDistinct by default for count queries

### ISSUE THREAD

**Issue by ewingrj** [feathersjs-ecosystem/feathers-objection#65]
Currently countDistinct is used for count queries:

https://github.com/feathersjs-ecosystem/feathers-objection/blob/df2c7a43bdf0c7a105cb925d55fcf6c5e0e63b6b/src/index.js#L341 

Testing in postgres, this is significantly slower (10x) then just a count query and also prevents parallelization by the dbms.

I would think that the default should not use countDistinct as most the majority of the time, the id column is going to be a pk which ensures uniqueness.

**Comment by daffl** [comment]
If all current tests are still passing, a PR would be accepted.

**Comment by dekelev** [comment]
The `countDistinct` is preventing duplicates issues when used with `joinRelation`. It cannot be simply changed back to count, but the solution may be revised.

**Comment by dekelev** [comment]
v4.4.3 changed `countDistinct` to be used only with `joinRelation` operator. otherwise, `count` will be used.
