### ISSUE TITLE
$joinRelation doesn't work within $or queries

### ISSUE THREAD

**Issue by ewingrj** [feathersjs-ecosystem/feathers-objection#68]
The join relation in the following query is ignored. I'd assume that the same is true for `$and`.

```
{
  $or:[
    { $joinRelation: 'child(exists)' },
    { success: true }
  ]
}
```

**Comment by dekelev** [comment]
What is the raw SQL query that you're trying to run using $or & $joinRelation?

$joinRelation should be used with $eager and only in the query object's root level and without conditioning.

**Comment by ewingrj** [comment]
something like: 

```
select * from parent join child on child.parent = parent.id where parent.success or child.id is not null```

**Comment by dekelev** [comment]
It should be possible. Maybe something like this?

query: {
  $eager: 'child(exists)',
  $joinRelation: 'child(exists)',
  $or: {
    $not: {
      id: null
    },
    success: true
  }
}

בתאריך יום ד׳, 16 באוק׳ 2019, 6:00, מאת RJ Ewing ‏<notifications@github.com
