### ISSUE TITLE
Allow creation of dynamic eager filters

### ISSUE THREAD

**Issue by ntsim** [feathersjs-ecosystem/feathers-objection#72]
The current API supports the ability to define eager filters (named or otherwise) upfront when the service is created, however, there doesn't seem to be any way to create dynamic eager filters from the client. In my use-case, I would like to be able to do something like the following:

```javascript
service.find({
  query: {
    $eager: {
      someRelation: {
    	userId: 1,
      }
    }
  }
});

// Or maybe some new operator like:

service.find({
  query: {
    $eager: 'someRelation'
    $filterEager: {
      someRelation: {
    	userId: 1,
      }
    }
  }
});
```

Where `userId` is a property on `someRelation`.

I would imagine this new API would also work with existing named eager filters:

```javascript
service.find({
  query: {
    $eager: {
      'someRelation(someNamedFilter)': {
        userId: 1
      }
    }
  }
});
```

And could even support most of the query operators:

```javascript
service.find({
  query: {
    $eager: {
      someRelation: {
    	userId: {
    	  $nin: [1, 2, 3]
    	}
      }
    }
  }
});
```

Having looked at the code, I can't think of why the above wouldn't be achievable given that the DSL already supports quite complex filtering on the root model. I'm no expert on Objection though, so I could obviously be missing something here!

**Comment by dekelev** [comment]
Try this:
```
query: {
  $eager: 'someRelation',
  'someRelation.userId': 1
}
```

**Comment by ntsim** [comment]
Thanks for the suggestion @dekelev, but I've found that none of those options (in various combinations) seem to work to achieve what I'm suggesting from the issue.

```
query: {
  $eager: 'someRelation',
  'someRelation.userId': 1,
}
```

The above will result in a `missing FROM-clause entry for table "someRelation"` error as `$eager` by itself will not be enough to be build the correct count query (when using pagination). Using `$joinEager` runs into the same problem unsurprisingly.

To get around this, we can try and use `$joinRelation`, like you suggested:

```
query: {
  $eager: 'someRelation',
  $joinRelation: 'someRelation',
  'someRelation.userId': 1,
}
```

This doesn't crash out, but we run into another issue in that the results aren't right. The `someRelation.userId` constraint is only applied to the root model queries and not the joined eager relation queries. Here's an example of this:

```json
{
  "total": 1,
  "limit": 10,
  "skip": 0,
  "data": [
    {
      "id": 1,
      "name": "Parent",
      "someRelation": [
        {
          "id": 1,
          "name": "Child A",
          "userId": 1
        },
        {
          "id": 2,
          "name": "Child B",
          "userId": 2
        }
      ]
    }
  ]
}
```

In the above, I do not expect `Child B` to be in the results as its `userId` is not 1. Note that other parent models have been filtered out if they do not have _any_ child with a `userId` of 1. This is also undesirable as I want to get all parents regardless of if they have a matching child or not. It should just be that the children _themselves_ are filtered.

This is how I've come around to the conclusion that we need some way to add dynamic eager filters as described in the issue.

I've actually hacked together an extended version of the `Service` class and it can be implemented fairly trivially (although definitely not ideal as I need to copy-pasta lots of internals to get it to work).

Here's the main snippet:

```javascript
createQuery(params = {}) {
  // rest of code...
  if (query && query.$filterEager) {
    Object.entries(query.$filterEager).forEach(
      ([eagerFilterExpression, eagerFilterQuery]) => {
        q.filterEager(eagerFilterExpression, builder => {
          this.objectify(builder, eagerFilterQuery);
        });
      },
    );

    delete query.$filterEager;
  }
}
```

**Comment by dekelev** [comment]
You shouldn't get any error. can you try with the actual table name in case it's different from the relation name?
for example:
```
query: {
  $eager: 'someRelation',
  'actualTableName.userId': 1,
}
```

**Comment by ntsim** [comment]
Nope still getting the same error. We end up producing this pagination count query:

```sql
select count("theParent"."id") as "total" from "theParent" where "someRelation"."userId" = 1
```

It looks like we'd be almost there, but this kind of query isn't really right as it implies we should be joining the two tables. This would in fact lead to an incorrect pagination total as I want to get all of the parents (parents should **not** be filtered out based on the child's constraint).

To get my desired result we need to be able to produce these queries:

```sql
select count("theParent"."id") as "total" from "theParent"
select "theParent".* from "someRelation" limit 3
select "someRelation".* from "someRelation" where "someRelation"."parentId" in (1, 2, 3) and "userId" = 1
```

`$joinRelation` is not the correct tool as I've mentioned earlier, so I think the only way seems to be to attach the `someRelation.userId` to the eager relationship via `filter/modifyEager`. Unfortunately this is not possible with the current API.

**Comment by dekelev** [comment]
Thanks @ntsim , try [$modifyEager](https://github.com/feathersjs-ecosystem/feathers-objection#query-operators) with v4.6.0

For example:
`companies.find({ query: { $eager: 'employees', $modifyEager: { employees: { name: 'John' } } } })`

**Comment by ilbrigz** [comment]
Hi! How do i use the $modifyEager query with REST?

**Comment by dekelev** [comment]
Hi @ilbrigz , `$modifyEager` format is just like the query format. a querystring can contain something like `$modifyEager[employees][name]=john`

**Comment by mdartic** [comment]
Hi @dekelev , I'm having some difficulties too to filter on a JSON field in a relation.

I've tried `$modifyEager[myEagerName][myJSONField.myProperty]=whatIWant`

But that's not working. No errors, but doesn't filter.

Do you know how I could use `$modifyEager` to make it filter on a JSON field ?

Thank you !

**Comment by dekelev** [comment]
@mdartic You can open a separated bug regarding this. `$modifyEager` currently does not support JSON fields.

**Comment by mdartic** [comment]
Thanks @dekelev for your answer and your great support.

I'm gonna live without ;-) I can have a service directly wired to the relation that was linked to the initial model.

I was just trying to make this in less REST requests, but that's fine with this limitation.

I'm not opening an issue for that since it's a limitation that can't be fixed.
