### ISSUE TITLE
Dependencies in ecosystem packages

### ISSUE THREAD

**Issue by vonagam** [feathersjs-ecosystem/feathers-objection#75]
`objection` is required [in sources](https://github.com/feathersjs-ecosystem/feathers-objection/blob/dc0e947e315187538f6c8638410ded6e83aa0ab5/src/index.js#L3) and [in types](https://github.com/feathersjs-ecosystem/feathers-objection/blob/dc0e947e315187538f6c8638410ded6e83aa0ab5/types/index.d.ts#L4) of `feathers-objection`, yet `objection` is listed only in [`devDependencies`](https://github.com/feathersjs-ecosystem/feathers-objection/blob/dc0e947e315187538f6c8638410ded6e83aa0ab5/package.json#L85).

Other ecosystem packages with similar situations:

**`mongoose`**: not used in sources but `mongoose` is in [`peerDependencies`](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/25ba7598e18e2f992eaf727fa8a85a0209e74baa/package.json#L62), types on the other hand [are used](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/25ba7598e18e2f992eaf727fa8a85a0209e74baa/types/index.d.ts#L4) but `@types/mongoose` is only in [`devDependencies`](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/25ba7598e18e2f992eaf727fa8a85a0209e74baa/package.json#L74).

**`mongodb`**: used [in sources](https://github.com/feathersjs-ecosystem/feathers-mongodb/blob/ebe4346a5e5769c12ae49843ccad170c73bca346/lib/index.js#L1) and [in types](https://github.com/feathersjs-ecosystem/feathers-mongodb/blob/ebe4346a5e5769c12ae49843ccad170c73bca346/types/index.d.ts#L4), both `mongodb` and `@types/mongodb` are listed only in [`devDependencies`](https://github.com/feathersjs-ecosystem/feathers-mongodb/blob/master/package.json#L68,L73).

**`knex`**: used [in types](https://github.com/feathersjs-ecosystem/feathers-knex/blob/2fabcb7699e6ad48956554d79756d5d2184c92d9/types/index.d.ts#L4), `knex` is only in [`devDependencies`](https://github.com/feathersjs-ecosystem/feathers-knex/blob/2fabcb7699e6ad48956554d79756d5d2184c92d9/package.json#L71).

**`elasticsearch`**: used [in types](https://github.com/feathersjs-ecosystem/feathers-elasticsearch/blob/738a22c6d9292cd13a6156cad4db2031bfb97c5f/types/index.d.ts#L4), `@types/elasticsearch` is only in [`devDependencies`](https://github.com/feathersjs-ecosystem/feathers-elasticsearch/blob/738a22c6d9292cd13a6156cad4db2031bfb97c5f/package.json#L55).

**`nedb`**: used [in types](https://github.com/feathersjs-ecosystem/feathers-nedb/blob/591b3a847c90b8a2658b43faacf72d561c9c8ab7/types/index.d.ts#L5), `@types/nedb` is only in [`devDependencies`](https://github.com/feathersjs-ecosystem/feathers-nedb/blob/591b3a847c90b8a2658b43faacf72d561c9c8ab7/package.json#L62).

**Comment by dekelev** [comment]
Thanks @vonagam, Added objection v1.x as peer-dependency in feathers-objection v4.6.4
