### ISSUE TITLE
Support for Objection v3 and deprecation of eager and joinEager

### ISSUE THREAD

**Issue by tmartensen** [feathersjs-ecosystem/feathers-objection#77]
I was looking at the documentation for `$eager` and `$joinEager`, and while viewing the Objection reference material, I see that the related `eager()` and `joinEager()` methods will be deprecated in Objection v3 in favor of `withGraphFetched` and `withGraphJoined`. Are there plans to change this API to reflect those deprecations, or will it be OK to continue using `$eager` and `$joinEager`?

**Comment by dekelev** [comment]
It's OK to keep using `$eager`, `$joinEager` & `$joinRelation` and they should still work fine with Objection v2.x, though you'll get deprecation warnings. I do recommend using Objection v1.6.11 until full support is added to feathers-objection, which I plan to do soon.
