### ISSUE TITLE
Error querying JSONB column

### ISSUE THREAD

**Issue by Adam-0-Moore** [feathersjs-ecosystem/feathers-objection#79]
I've seen issues [62](https://github.com/feathersjs-ecosystem/feathers-objection/issues/62) and [74](https://github.com/feathersjs-ecosystem/feathers-objection/issues/74) and read the [JSON section of the readme](https://github.com/feathersjs-ecosystem/feathers-objection#json-column). I'm still getting errors - not sure if it's me or a bug

"objection": "^2.0.10"
"feathers-objection": "^4.7.0"
"knex": "^0.20.6"
"pg": "^7.17.0"

```
 class category extends Model {

  static get tableName() {
    return 'data.category';
  }

  static get idColumn() {
    return 'id';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: [],
      properties: {
        id: 'integer',
        info: {
          type: 'object',
          required: [],
          properties: {
            one: {
              type: 'object',
              required: [],
              properties: {
                old: 'string',
                new: 'string'
              }
            },
            two: 'string',
            three: 'string'
          }
        }
      }
    }
  }
}
```
This is the query I'm using
```
findQuery() {
      return {
        $sort: {
          id: 1
        },
        $limit: 100,
        info: {
          one: {
            new: {
              $ilike: '%eggs%'
            }
          }
        }
      }
    }
```
And I get this error, leading me to believe I formed the query wrong. Although, it does look like the query in issue 74 that works

```
431[{"name":"Forbidden","message":"select \"data\".\"category\".* from \"data\".\"category\" where \"new\" ilike $1 order by \"id\" asc limit $2 - column \"new\" does not exist","code":403,"className":"forbidden","errors":{}}]
```
I also tried changing the query
```
findQuery() {
      return {
        $sort: {
          id: 1
        },
        $limit: 100,
        info: {
          'one.new': {
            $ilike: '%eggs%'
           }
        }
      }
    }
```
getting this error:
```
431[{"name":"Forbidden","message":"select \"data\".\"category\".* from \"data\".\"category\" where \"one\".\"new\" ilike $1 order by \"id\" asc limit $2 - missing FROM-clause entry for table \"one\"","code":403,"className":"forbidden","errors":{}}]
```
And one last test:
```
findQuery() {
      return {
        $sort: {
          id: 1
        },
        $limit: 100,
        'info.one.new': {
           $ilike: '%eggs%'
          }
       }
     }
   }
```
getting this error:
```
431[{"name":"Forbidden","message":"select \"data\".\"category\".* from \"data\".\"category\" where \"info\".\"one\".\"new\" ilike $1 order by \"id\" asc limit $2 - missing FROM-clause entry for table \"one\"","code":403,"className":"forbidden","errors":{}}]
```
I've double checked the spelling of the column/object names. Am I doing something wrong, or is it not meant to work like this?

Directly in the PostgreSQL database this query works:
```
select * from data.category where info -> 'one' ->> 'new' ilike '%eggs%'
```

**Comment by Aerlin** [comment]
I was able to get your 2nd query to work but only when the table name didn't have a period in it. Otherwise it gave me a 
`Forbidden: select count("data"."category"."id") as "total" from "data"."category" where CAST("data"."category"."info"#>>'{one,new}' AS text) ilike $1 - relation "data.category" does not exist` 
error, different from what you're getting. Weird :-/

**Comment by Adam-0-Moore** [comment]
In my case the table name doesn't have a period, it's actually the schema plus the table. I'm not sure the best way to use schema, but I saw somewhere to include it in the table name and it seems to work. Maybe that's why the different error?

**Comment by dekelev** [comment]
Knex doesn't seems to support dot notation in table or column names: https://github.com/knex/knex/issues/2762#issuecomment-414003096
