### ISSUE TITLE
Add error handling API

### ISSUE THREAD

**Issue by ntsim** [feathersjs-ecosystem/feathers-objection#80]
Currently this adapter does not provide any API to modify its error handling behaviour and by default it simply converts any Objection errors into a `FeathersError`.

Unfortunately, this leads to leakage of database details in the form of error messages that usually contain the SQL that Objection is trying to execute. This should be considered a security vulnerability as it can be potentially used by malicious actors.

As `FeathersError` strip out any information from the original error, it makes it difficult to intercept the error and determine its original Objection error type so that we can re-map the error message. The Objection docs essentially suggest this is what you should be doing: https://vincit.github.io/objection.js/recipes/error-handling.html

Interestingly, `feathers-knex` already offers an escape hatch that allows you to access the underlying original error: https://github.com/feathersjs-ecosystem/feathers-knex#error-handling
This could perhaps serve as the frame of reference for where the API should go.

**Comment by dekelev** [comment]
Thanks @ntsim, I'm releasing v4.8.0 with update to the [error handler](https://github.com/feathersjs-ecosystem/feathers-objection#error-handling).
