### ISSUE TITLE
Please add an example of how to use transaction

### ISSUE THREAD

**Issue by devashishsethia** [feathersjs-ecosystem/feathers-objection#81]
Hi,
Thanks for your awesome work!
This is not an issue per se, but I haven't been able to get my head around how to use transactions. Since transactions are required in any real life project, a simple example in the docs could help us a lot. 

Thanks in advance.

**Comment by dekelev** [comment]
Hi @devashishsethia, thanks for the feedback. I've added some more info and link on the subject [here](https://github.com/feathersjs-ecosystem/feathers-objection#transaction).

A full example is available [here](https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/test/index.test.js#L1442).

**Comment by devashishsethia** [comment]
Thank you so much! Got it working with your help. I've created a set of simple feathers hooks that can be added to the project or docs, if you would like (startTransaction() method mentioned in the objection docs didn't work for me). Couldn't create a pull request.

```
const {transaction} = require('objection');
// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/api/hooks.html

// eslint-disable-next-line no-unused-vars

const start = (options = {}) => {
  return async context => {
    const { service } = context;
    const Model = service.Model;
    const trx = await transaction.start(Model); // use Model if you have installed a knex instance globally using the Model.knex() method, otherwise use Model.knex()
    context.params.transaction = { trx };
    return context;
  };
};

const commit = (options = {}) => {
  return async context => {
    const { transaction } = context.params;
    await transaction.trx.commit();
    return context;
  };
};

const rollback = (options = {}) => {
  return async context => {
    const { transaction } = context.params;
    await transaction.trx.rollback();
  };
};

module.exports = {
  _transaction: {
    start,
    commit,
    rollback
  }
};
```

**Comment by devashishsethia** [comment]
If you have configured knex using app.set('knex', knex) in objection.js (If you used feathers-cli, that should be the case), you can also start the transaction without using Model like so:
```
const start = (options = {}) => {
  return async context => {
    const { service, app } = context;
    const knex = app.get('knex');
    const trx = await transaction.start(knex);
    context.params = {
      ...context.params,
      transaction: {
        trx
      }
    }
    return context;
  };
};
```

**Comment by Artaud** [comment]
This should definitely be in the docs.
