### ISSUE TITLE
When patching object A that has many Bs, instead of inserting new B, B is overwritten with new id

### ISSUE THREAD

**Issue by domagoj-orioly** [feathersjs-ecosystem/feathers-objection#84]
I have model A that hasMany B records.

```
// A.model.js
  static get relationMappings() {
    return {
        Bs: {
            relation: Model.HasManyRelation,
            modelClass: B,
            join: {
                from: 'A.id',
                to: 'B.a_id'
            }
        }
    }
}
```

```
A.service.js

...

  const options = {
    Model: createModel(app),
    paginate: app.get('paginate'),
    whitelist: ['$joinRelation', '$eager'],
    allowedInsert: '[B]',
    allowedEager: '[B]',
    allowedUpsert: '[B]',
    createUseUpsertGraph: true,
  };
```

And when I patch A object, record in the database in table B gets overwritten  with new id, instead of new record being inserted. The only way B could be located is by `B.a_id` column. 

I'm trying to insert it like:

```
service('A').patch(id, { ..., Bs: [ { someData } ] });
```

If it's of any help, I'm trying to do this in two separate patch requests. Doing it in one, for example, with multiple B objects, yields same result, both records are overwritten, each with new ID. Note that I'm not providing an existing IDs in Bs array.

Am I missing something or is this how it's supposed to be?

**Comment by dekelev** [comment]
I'm not sure, but you can control the behavior by setting the service option `upsertGraphOptions` with the desired configuration from [here](https://vincit.github.io/objection.js/api/types/#type-upsertgraphoptions).
