### ISSUE TITLE
$joinEager does not using join at total data

### ISSUE THREAD

**Issue by taufiqurrohmansuwarto** [feathersjs-ecosystem/feathers-objection#85]
when using $joinEager count doesnt use join in total (count) but when im using $joinRelation the count is using inner join. Is this bug? it always give me error when i tried filter from $eager column

**Comment by dekelev** [comment]
This is the expected behavior. what are you trying to achieve and what errors do you get? please share detailed examples.

**Comment by taufiqurrohmansuwarto** [comment]
heres my table
![image](https://user-images.githubusercontent.com/26428809/76089718-cc232f80-5fec-11ea-95a2-8f6069156f78.png)

and heres my model (kamus)
static get relationMappings() {
    const tipeKamusModel = require("./tipe-kamus.model");
    const subKamusModel = require("./sub-kamus.model");
    const skpdModel = require("./skpd.model");

    return {
      tipeKamus: {
        modelClass: tipeKamusModel,
        relation: Model.BelongsToOneRelation,
        join: {
          from: "kom.kamus.tipe_kamus_id",
          to: "kom.tipe_kamus.id"
        }
      },
      subKamus: {
        modelClass: subKamusModel,
        relation: Model.HasManyRelation,
        join: {
          from: "kom.kamus.id",
          to: "kom.sub_kamus.kamus_id"
        }
      },
      skpd: {
        modelClass: skpdModel,
        relation: Model.BelongsToOneRelation,
        join: {
          from: "kom.kamus.skpd_id",
          to: "ref.skpd.id"
        }
      }
    };
  }

my goal is to get data where kamus.skpd_id ilike 'something%' but include tipeKamus and skpd and kamus.skpd_id is null of course.

my current query is {
	$eager : '[tipeKamus]',
	$joinEager : '[tipeKamus,skpd],
        'skpd.id' : {
	  $ilike : 'something%',
	}		
}

it giving me error because in count there isnt column skpd.id


well what a shame i got a solution.. now its working. im sorry

{

$eager: '[tipeKamus, skpd]',
                $joinEager: '[tipeKamus,skpd]',
                $or: [
                  {
                    skpd_id: {
                      $null: true,
                    },
                  },
                  {
                    skpd_id: {
                      $ilike: `123%`,
                    },
                  },
                ],
}
