### ISSUE TITLE
filters without eager queries

### ISSUE THREAD

**Issue by devashishsethia** [feathersjs-ecosystem/feathers-objection#86]
Hi,

Does feathers-objection support using filters without using it in a eager query? Like how we can do with Objection:

```
class Person extends Model {
  static modifiers = {
    defaultSelects(query) {
      query.select('id', 'firstName');
    },

    filterGender(query, gender) {
      query.where('gender', gender);
    }
  };
}
```
```
const women = await Person.query()
  .modify('defaultSelects')
  .modify('filterGender', 'female');
```

It would be great if we can pass a $modify query parameter and use static modifiers.
Thanks.

**Comment by dekelev** [comment]
Thanks @devashishsethia , `$modify` is now supported in the latest version. check the [docs](https://github.com/feathersjs-ecosystem/feathers-objection#query-operators) for more info.

**Comment by prashantnirgun** [comment]
Hi to community I am new to it can any one explain how to give call to $modify using post man I want to use this in GET request
from postman 
GET localost:3000/perosn?$modify=filterGender=['gender', 'female'] its considering $modify as a column and adding it to where clause.

**Comment by devashishsethia** [comment]
I hope you've created the modifier in your model. $modify will be an array,
so it will have to be used like ?$modify[]=filterGender&$modify[]=female



Regards,
Devashish Sethia
