### ISSUE TITLE
How to alias a column that is ambiguous in $joinRelation?

### ISSUE THREAD

**Issue by domagoj-orioly** [feathersjs-ecosystem/feathers-objection#87]
I have a $joinRelation property relating couple of tables and I receive sql error saying that `... "x" column is ambiguous in where clause.` How and where can I alias the said column? I've only come across this question https://stackoverflow.com/questions/51411208/objectionjs-column-reference-is-ambiguous but I don't use `where` clauses myself so I would need to modify the alias somewhere else. 

I've tried looking up Objection.js documentation about relationships and trying to see if there is a way to prefix the column with an alias but no luck so far.

**Comment by dekelev** [comment]
Add table to the column. For example:
{ query: { 'table.column': 1 }

**Comment by mariusandra** [comment]
Hi! I ran into this as well. The suggested fix will work, but it will break `$eager: 'user'` from returning anything.

**Comment by dekelev** [comment]
Hi @mariusandra , if you have an issue, please open a new one with examples.

**Comment by mariusandra** [comment]
It's not an issue for me. I worked around it by making 2 queries and it was a throwaway project anyway.
I though I'll just leave a breadcrumb here for if anyone googling has a similar case. This person can then make a real issue :)
