### ISSUE TITLE
feathers-objection/types has no exported member 'ERROR'

### ISSUE THREAD

**Issue by robbyphillips** [feathersjs-ecosystem/feathers-objection#93]
There is a small issue with the exported types.  Doing a `import { ERROR } from 'feathers-objection'` throws a typescript error because the `index.d.ts` file doesn't include it.  The symbol is still imported and everything works fine with a `// @ts-ignore` directive.

Edit:

I think we just need to change the `declare const objection` bit to something more like

```
declare const objection: {
  <T>(config?: Partial<ObjectionServiceOptions>): Service<T>
  ERROR: Symbol
}
```
https://www.typescriptlang.org/docs/handbook/interfaces.html#hybrid-types

**Comment by dekelev** [comment]
@daffl , can you please take a look at this?
