### ISSUE TITLE
How to compare a field to another field

### ISSUE THREAD

**Issue by ranielzed** [feathersjs-ecosystem/feathers-objection#96]
Hi,

I'm trying to compare two fields inside a modifyEager. 
I read about 'ref' but I can't seem to make it work.

Is this possible?
`client.service('invoice').find({
          query: {
            $and: [
              {
                'invoice.updated_at': {
                  $gt: stDate.toISOString(),
                },
              },
              {
                'invoice.updated_at': {
                  $lt: endDate.toISOString(),
                },
              },
            ],
            $joinEager: '[products.pricing, cashier]',
            $modifyEager: {
              'products.pricing': {
                $and: [
                  {
                    start_date: {
                      $lt: `**COMPARE TO invoice.updated_at,** `,
                    },
                  },
                  {
                    end_date: {
                      $gt: `**COMPARE TO invoice.updated_at,**`,
                    },
                  },
                ],
              },
            },
          },
        })`

**Comment by dekelev** [comment]
I've added `$allowRefs` query operator in v5.5.0 to be able to reference another field. See [docs](https://github.com/feathersjs-ecosystem/feathers-objection#query-operators) for more info.

BTW, you can use `$between` query operator and you better use `$joinEager` or `$joinRelation` instead of `$modifyEager` for this use-case. you won't need the `$and` operator too in this case.

**Comment by ranielzed** [comment]
Thank you so much for the help.

Also thanks for the tips. That made it simpler and easier to read.

However, I need your help again as I can't seem to make it work. This is what I have now:
`      client
        .service('invoice')
        .find({
          query: {
            $joinRelation: '[cashier, products.pricing]',
            $and: [
              {
                'invoice.updated_at': { $between: [stDate.toISOString(), endDate.toISOString()] },
              },
              {
                'invoice.updated_at': {
                  $between: ['ref(products:pricing.start_date)', 'ref(products:pricing.end_date)'],
                },
              },
            ],
            $allowRefs: true,
          },
        })`

**These are the steps I did:**

1. Tried ref with between but between seems to treat it as a value still. Looking at the debug logs, I saw this: `bindings: [
     '2020-05-22T00:00:00.000Z',
     '2020-05-22T23:59:59.999Z',
     'ref(products:pricing.start_date)',
     'ref(products:pricing.end_date)'
   ]`

2. Tried ref with $gt (`
                'invoice.updated_at': {
                  $gt: 'ref(products:pricing.start_date)',
                }`)
and I got this from the logs: `where (("invoice"."updated_at" between ? and ?) and ("invoice"."updated_at" > "products"#>'{pricing,start_date}'))`
It seems it was not able to parse the fields correctly.

**Comment by dekelev** [comment]
Replace the colon with dot, e.g. it should like this
ref(products.pricing.start_date)

בתאריך יום ו׳, 22 במאי 2020, 14:46, מאת ranielzed ‏<notifications@github.com

**Comment by ranielzed** [comment]
@dekelev 
thank you for the help. But it still is being passed as parameters:

**Logs:**
`method: 'select',
   options: {},
   timeout: false,
   cancelOnTimeout: false,
   bindings: [
     '2020-05-25T00:00:00.000Z',
     '2020-05-25T23:59:59.999Z',
     'ref(products.pricing.start_date)',
     'ref(products.pricing.end_date)'
   ],
   sql: 'select count("invoice"."id") as "total" from "invoice" where (("invoice"."updated_at" between ? and ?) and ("invoice"."updated_at" between ? and ?))'
}
`

**Comment by dekelev** [comment]
@ranielzed I can't help any further without full example to reproduce here.
