### ISSUE TITLE
query params ignored for calls to patch for a service with allowUpsert 

### ISSUE THREAD

**Issue by nakedgun** [feathersjs-ecosystem/feathers-objection#97]
I came across this issue when writing some tests to validate the security of an API. In one of the tests, it validates that calls to patch() a resource are limited to the owning user, which is a fairy common requirement in most APIs.

As a simple example, using [feathers-authentication-hooks](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks), here the patch method will rewrite the userId in the query, effectively causing calls made by a user which doesn't own the resource to return 404.

```
const { setField } = require('feathers-authentication-hooks');
const limitToUser = setField({
  from: 'params.user.id',
  as: 'params.query.userId'
});

  before: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [
      authenticate('jwt'),
      limitToUser
    ],
    remove: []
  },
```

If you update the service to include 'allowedUpsert`, the call to patch ignores the userId set on the query. In this scenario this means user2 could update user1's resource. 

```
const options = {
    Model: createModel(app),
    paginate: app.get('paginate'),
    whitelist: ['$eager'],
    allowedEager: '[images]',
    allowedUpsert: 'images'
  };
```

This isn't specific to the userId - any params which are set on the query are ignored if  **allowedUpsert** is enabled. This doesn't repro for calls to update.

I believe this is a bug, since the behavior is not documented, and it goes against the expected behavior of patch() - but if not, curious as to why this happens and what the best practice is here. Thanks for your help!

**Comment by dekelev** [comment]
@nakedgun Thanks for the detailed report.

`allowedUpsert` runs Objection's `upsertGraphAndFetch` method in calls to patch & update.

The behavior of [ObjectionJS upsertGraphAndFetch](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#upsertgraphandfetch) is documented [here](https://vincit.github.io/objection.js/guide/query-examples.html#graph-upserts):

"By default upsertGraph method updates the objects that have an id, inserts objects that don't have an id and deletes all objects that are not present. This functionality can be modified in many ways by providing [UpsertGraphOptions](https://vincit.github.io/objection.js/api/types/#type-upsertgraphoptions) object as the second argument.

The upsertGraph method works a little different than the other update and patch methods. When using upsertGraph **any where or having methods are ignored**. The models are updated based on the id properties in the graph. This is also clarified in the examples."

**Comment by nakedgun** [comment]
@dekelev gotcha, thanks for the clarification. What's confusing is that with upsertGraph enabled, this hook will still modify the query for `update` - just not `patch`. Might be nice to update the feathers-objection docs so others are aware of this caveat -- since it can so easily break hooks which enforce auth.

**Comment by dekelev** [comment]
I'm not sure what you mean. `update` ignores the query object in general, because update in any Feathers DB adapter is ment to update all fields on a record by ID. It's not unique to feathers-objection - https://docs.feathersjs.com/api/databases/common.html#adapter-update-id-data-params

**Comment by nakedgun** [comment]
>update ignores the query object in general, because update in any Feathers DB adapter is ment to update all fields on a record by ID

@dekelev I don't think that's true. All service methods still respect the query object. For example:

```
const { setField } = require('feathers-authentication-hooks');
const { authenticate } = require('@feathersjs/authentication').hooks;
// some service hooks
    update: [
      authenticate('jwt'),
      setField({
        from: 'params.user.id',
        as: 'params.query.userId'
      }),
    ],
```
POST /messages/1  (authenticated)

```
api_1       |   knex:query select count("messages"."id") as "total" from "messages" where "userId" = ? and "messages"."id" = ? undefined +8ms
api_1       |   knex:bindings [ 2, '1' ] undefined +8ms
api_1       |   knex:client releasing connection to pool: __knexUid6 +4ms
api_1       |   knex:client acquired connection from pool: __knexUid6 +1ms
api_1       |   knex:query select "messages".* from "messages" where "userId" = ? and "messages"."id" = ? limit ? undefined +6ms
api_1       |   knex:bindings [ 2, '1', 100 ] undefined +6ms
```

Here you will see the hook rewrites the userId on the query object, which is used as part of the ID lookup - a common strategy for [restricting access](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks) to service models.

Looking in the feathers-objection source, you'll notice for **update** it will first call [this._get(id,params)](https://github.com/feathersjs-ecosystem/feathers-objection/blob/de3f17e0b251318317aa60d4e89a51ae1417c44d/src/index.js#L531) which uses the query object in the[ find()](https://github.com/feathersjs-ecosystem/feathers-objection/blob/de3f17e0b251318317aa60d4e89a51ae1417c44d/src/index.js#L455) call to lookup the entity by ID.

Going back to the original point of this case, all service methods in feathers **respect** params in the query object. The anomalous behavior here is query params are ignored for patch() **if allowUpsert is used**, which caught me out, and I imagine it will for other developers too.

I hope that helps clarify things!

**Comment by dekelev** [comment]
@daffl Can you please join this discussion?

**Comment by daffl** [comment]
I am not using or know much about Objection.js so I don't really have any suggestions other than not allowing upserts.

**Comment by Thomas-git** [comment]
I think upsertGraph should only be used when id===data.id and there is no query in params because as @dekelev stated, all information to the action IS IN the data. And it's a pretty dangerous function (see warnings in the docs). Merging query params in upsertGraph data can lead to unexpected behavior.

So the things that could be done in patch:
Throw if upsertGraph is used with a query : would have prevented @nakedgun mistake
Throw if patch 'id' and data.id missmatch with upsertGraph (instead of copying them silently)

And in update:
Throw if used with a query (per feathers doc) 
if upsertGraph : auto add $eager to _get params with the same relation as in allowedUpsert, because as is, '_get' will wipe all data not existing in the fetched object.
Throw if update 'id' and data.id missmatch with upsertGraph (because now you get an object and may update another !)

I may do it if it makes sense for everybody.

**Comment by dekelev** [comment]
Thanks @Thomas-git, sounds good! any PR is welcome

**Comment by Thomas-git** [comment]
@dekelev  Also, while I worked on it, I found usage of $select and $noSelect does not give a reproducible result :
* patch single and patch batch return user selected items (or no selection)
* But patch upsert, update and update upsert do not honor user selection at all.

Do you agree $select and $noSelect should be honored in all cases ?

**Comment by dekelev** [comment]
Yes, it should be supported withing the upsert actions too.

בתאריך יום ג׳, 15 בספט׳ 2020, 17:42, מאת Thomas-git ‏<
notifications@github.com>:
